### ISSUE TITLE
A question about function "adaptor::elem_ptr"

### ISSUE THREAD

**Issue by Tomoki-0526** [Eleobert/dbscan#2]
Thanks for your work!

I'm confused about the returned value of function "adaptor::elem_ptr": 

```cpp
auto const * elem_ptr(const std::size_t idx) const
    {
        return &points[idx].x;
    }
```

Why does it return the address of 'x' but not the address of points[idx]? If I want to use other type of data such as a customized iterators, how do I modify?

**Comment by Eleobert** [comment]
It returns a pointer to the element type because it is what the `KDTreeSingleIndexAdaptor` expects. Otherwise, I would have to cast it back to element type when calling `radiusSearch`. 

You need to make sure that in memory, different dimensions of a single point are adjacent: x, y, z, x, y, z,...z; which again in this case is the address of x.

It is a long time since I last checked nanoflann, and at this point the API may have changed, you might want to take this into consideration.
